# Generated by Django 2.0.2 on 2018-03-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigningAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Booked Asset', max_length=20)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_set', to=settings.AUTH_USER_MODEL)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
