# Generated by Django 2.0.2 on 2018-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assigningasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigningasset',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
