# Generated by Django 2.0.2 on 2018-03-05 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assigningasset_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boss_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
